### ISSUE TITLE
Crashes on opening schema.prisma

### ISSUE THREAD

**Issue by TriupLauro** [pantharshit00/coc-prisma#25]
When I open the schema.prisma file I am greeted with this error

```
[coc.nvim]: UnhandledRejection: Cannot find module '@prisma/language-server/dist
/src/bin'
Require stack:
- /home/valou/.config/coc/extensions/node_modules/coc-prisma/lib/index.js
- /home/valou/.config/coc/extensions/node_modules/coc-prisma/lib/index.js
Error: Cannot find module '@prisma/language-server/dist/src/bin'
Require stack:
- /home/valou/.config/coc/extensions/node_modules/coc-prisma/lib/index.js
- /home/valou/.config/coc/extensions/node_modules/coc-prisma/lib/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
    at req.resolve (/home/valou/.local/share/nvim/plugged/coc.nvim/build/index.j
s:77950:38)
    at Object.activate (/home/valou/.config/coc/extensions/node_modules/coc-pris
ma/lib/index.js:11:34)
    at /home/valou/.local/share/nvim/plugged/coc.nvim/build/index.js:78821:53
    at new Promise (<anonymous>)
    at Object.activate (/home/valou/.local/share/nvim/plugged/coc.nvim/build/ind
ex.js:78807:22)
    at /home/valou/.local/share/nvim/plugged/coc.nvim/build/index.js:78580:57
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5
)
```
And then
```
[coc.nvim] view.sync timeout, force render, view.sync may cause deadlock due to 
recursive calls
[coc.nvim] release is not a function
```

Syntax highlight still works, but not linting.

Here's the plugin part of init.vim

```nvim
call plug#begin()

Plug 'neoclide/coc.nvim', {'branch' : 'release'}
Plug 'HerringtonDarkholme/yats.vim'
Plug 'williamboman/mason.nvim'
Plug 'nvimtools/none-ls.nvim'
Plug 'jay-babu/mason-null-ls.nvim'
Plug 'natecraddock/workspaces.nvim'
Plug 'pantharshit00/vim-prisma'

call plug#end()
```

Here's the output of :CocInfo

```
## versions

vim version: NVIM v0.7.2
node version: v20.12.2
coc.nvim version: 0.0.82-c3ae5c3b 2024-05-23 20:39:40 +0800
coc.nvim directory: /home/valou/.local/share/nvim/plugged/coc.nvim
term: xterm-256color
platform: linux

## Log of coc.nvim

2024-07-09T08:39:31.973 WARN (pid:12279) [workspace] - Extension "coc-lists" registered synchronized autocmd "VimLeavePre", which could be slow.
2024-07-09T08:39:32.006 INFO (pid:12279) [plugin] - coc.nvim initialized with node: v20.12.2 after 1009
2024-07-09T08:40:35.151 INFO (pid:12279) [attach] - receive notification: installExtensions []
```

I don't really know what's relevant, I'm still a nvim beginner.

**Comment by airRnot1106** [comment]
Perhaps that error has been resolved in v0.12.0

https://github.com/pantharshit00/coc-prisma/releases/tag/v0.12.0

**Comment by TriupLauro** [comment]
It works now. Big thanks !
